### ISSUE TITLE
Improve importing other projects

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#138]
Importing other projects is not perfect right now, especially when it comes to required parameters. Maybe an explicit import as part of the project definition would be better:

```yaml
# Other project
name: raw-exporter

import:
  # Import with no (or default) parameters
  - poject: some_other_project
    
  # Import project with specified job context
  - project: aggregates
    # The job may even be a variable, so different job context can be imported
    job: $job
    parameters:
      processing_datetime: $processing_datetime

```
