### ISSUE TITLE
Implement "rearrange" mapping for renaming/extracting columns

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#26]
We could reuse the "explode" logic like
```
mappings:
  my_rearrangement:
      kind: arrange
      rename:
        cardId: nested.id
      lift:
        - nested.some_column
        - nested2.*
      keep:
        - occuredAt
        - dataOperation
        - nested4.some_column
      drop:
        - lala
        - nested.some_column
```

Implementation hint: Eithe one of the two strategies should be usded:
1. rename + keep + lift
2. rename - drop + lift
