### ISSUE TITLE
Support templates

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#27]
For recurring definitions, some templating mechanism would be very helpful. Either use something like follows
```
templates:
  mappings:
    lala_mapping_template:
      kind: assemble

mappings:
    lala_mapping_instance:
      kind: template
      parameters:
         xyz: abc
```
or maybe even simpler
```
mappings:
    lala_mapping_template:
      kind: assemble
      input: ${xyz}

    lala_mapping_instance:
      kind: template
      parameters:
         xyz: abc
```
