### ISSUE TITLE
Support column prefixes in assemble mapping

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#28]
When flattening nested structures, a prefix would be helpful
```
mappings:
  transmission_channel_updates:
    kind: assemble
    input: transmission_channel_explode
    columns:
      - kind: append
        path: channel
        prefix: channel_
        drop: recipients

```
