### ISSUE TITLE
Implement 'flatten' mapping

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#29]
For flattening nested structures, an according mapping is required
```
mappings:
    struct_flat:
      kind: flatten
      input: struct_nested
      naming: camelCase
```
Maybe this could also be implemented as part of the 'conform' mapping
