### ISSUE TITLE
Parametrize when to execute a specific phase

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#297]
```yaml
jobs:
  main:
    phases:
      # always (default) - execute always
      # first - execute only in first loop
      # last - execute only in last loop
      #
      # alternative default:
      validate: first
      create: first
      build: always
      verify: last
      truncate: always
      destroy: last

```
