### ISSUE TITLE
Parametrize when to execute each target

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#298]
```yaml
jobs:
  main:
    targets:
      # always (default) - execute always
      # first - execute only in first loop
      # last - execute only in last loop
      # never - execute never
      - name: some_full_load_target
        when: first
      - some_incremental_target
      - name: some_other_incremental_target
        when: always
      - name: documentation
        when: last
```
