### ISSUE TITLE
SQL assertions do not support empty strings as expected values

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#452]
Example:

```yaml
kind: sql
tests:
 - query: SELECT _1, _2 FROM mx
   expected:
     - [A,1]
     - [B,""]
     - [C,null]
```
