### ISSUE TITLE
Implement Flow-Control Mapping

### ISSUE THREAD

**Issue by kupferk** [dimajix/flowman#83]
A simple flow control depending on env-variables could be implemented as follows

```yaml
mappings:
  switch:
    kind: case
    cases:
      - condition: ${some_condition}
        mapping: other_mapping
      - condition: ${some_other_condition}
        mapping: some_other_mapping
      - condition: true
        mapping: some_other_mapping
```
Similar entities can be provided for relations and targets.
